"""add camp recommendation fields

Revision ID: 6dd3333cf9aa
Revises: 7099f34fbf92
Create Date: 2026-04-07 16:11:14.242580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd3333cf9aa'
down_revision = '7099f34fbf92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amenities', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('style_tags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.drop_column('style_tags')
        batch_op.drop_column('amenities')

    # ### end Alembic commands ###
