"""expand camp fields for csv data

Revision ID: ec93418a5f6a
Revises: 6dd3333cf9aa
Create Date: 2026-04-07 17:30:54.198814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec93418a5f6a'
down_revision = '6dd3333cf9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poi_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('tel', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('camp_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('typecode', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('business_area', sa.String(length=120), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('price_per_night',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_camps_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_camps_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_camps_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_camps_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_camps_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_camps_poi_id'), ['poi_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_camps_province'), ['province'], unique=False)
        batch_op.drop_column('amenities')
        batch_op.drop_column('style_tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_tags', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('amenities', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_camps_province'))
        batch_op.drop_index(batch_op.f('ix_camps_poi_id'))
        batch_op.drop_index(batch_op.f('ix_camps_name'))
        batch_op.drop_index(batch_op.f('ix_camps_longitude'))
        batch_op.drop_index(batch_op.f('ix_camps_latitude'))
        batch_op.drop_index(batch_op.f('ix_camps_district'))
        batch_op.drop_index(batch_op.f('ix_camps_city'))
        batch_op.alter_column('price_per_night',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('business_area')
        batch_op.drop_column('typecode')
        batch_op.drop_column('camp_type')
        batch_op.drop_column('tel')
        batch_op.drop_column('province')
        batch_op.drop_column('district')
        batch_op.drop_column('address')
        batch_op.drop_column('poi_id')

    # ### end Alembic commands ###
